[package]
name = "contract-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs.workspace = true
gbuiltin-staking.workspace = true
gstd.workspace = true

[dev-dependencies]
sails-rs = { workspace = true, features = ["gstd", "std"] }
tokio.workspace = true